using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

namespace SourceGeneratorDemo.Generators;

/// <summary>
/// Incremental source generator that implements INotifyPropertyChanged.
/// Fields decorated with [AutoNotify] get a corresponding public property
/// with change notification, eliminating repetitive MVVM boilerplate.
/// </summary>
[Generator]
public class AutoNotifyGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Inject the marker attribute + INotifyPropertyChanged base helper.
        context.RegisterPostInitializationOutput(static ctx =>
        {
            ctx.AddSource("AutoNotifyAttribute.g.cs", SourceText.From(AttributeSource, Encoding.UTF8));
        });

        // Find all fields with [AutoNotify] and group by containing type.
        IncrementalValuesProvider<NotifyClassInfo> pipeline =
            context.SyntaxProvider
                .ForAttributeWithMetadataName(
                    fullyQualifiedMetadataName: "SourceGeneratorDemo.Generators.AutoNotifyAttribute",
                    predicate: static (node, _) => node is VariableDeclaratorSyntax,
                    transform: static (ctx, _) => GetFieldInfo(ctx))
                .Where(static f => f is not null)
                .Select(static (f, _) => f!.Value)
                .Collect()
                .SelectMany(static (fields, _) =>
                {
                    // Group fields by their containing type.
                    return fields
                        .GroupBy(f => f.ContainingTypeFullName)
                        .Select(g => new NotifyClassInfo(
                            TypeName: g.First().TypeName,
                            Namespace: g.First().Namespace,
                            FullyQualifiedName: g.Key,
                            Fields: g.Select(f => new FieldInfo(f.FieldName, f.FieldType, f.PropertyName)).ToImmutableArray()))
                        .ToImmutableArray();
                });

        context.RegisterSourceOutput(pipeline, static (spc, classInfo) =>
        {
            var source = GenerateNotifyClass(classInfo);
            spc.AddSource(
                $"{classInfo.FullyQualifiedName.Replace(".", "_")}.AutoNotify.g.cs",
                SourceText.From(source, Encoding.UTF8));
        });
    }

    private static FieldCandidate? GetFieldInfo(GeneratorAttributeSyntaxContext context)
    {
        if (context.TargetSymbol is not IFieldSymbol fieldSymbol)
            return null;

        var containingType = fieldSymbol.ContainingType;
        var ns = containingType.ContainingNamespace.IsGlobalNamespace
            ? null
            : containingType.ContainingNamespace.ToDisplayString();

        var fieldName = fieldSymbol.Name;
        var propertyName = GetPropertyName(fieldName);

        return new FieldCandidate(
            FieldName: fieldName,
            FieldType: fieldSymbol.Type.ToDisplayString(),
            PropertyName: propertyName,
            TypeName: containingType.Name,
            Namespace: ns,
            ContainingTypeFullName: containingType.ToDisplayString());
    }

    private static string GetPropertyName(string fieldName)
    {
        // _name -> Name, name -> Name, _n -> N
        if (fieldName.StartsWith("_") && fieldName.Length > 1)
            return char.ToUpperInvariant(fieldName[1]) + fieldName.Substring(2);

        return char.ToUpperInvariant(fieldName[0]) + fieldName.Substring(1);
    }

    private static string GenerateNotifyClass(NotifyClassInfo info)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System.ComponentModel;");
        sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine();

        if (info.Namespace is not null)
        {
            sb.AppendLine($"namespace {info.Namespace}");
            sb.AppendLine("{");
        }

        sb.AppendLine($"    partial class {info.TypeName} : INotifyPropertyChanged");
        sb.AppendLine("    {");

        // Event
        sb.AppendLine("        public event PropertyChangedEventHandler? PropertyChanged;");
        sb.AppendLine();
        sb.AppendLine("        private void OnPropertyChanged([CallerMemberName] string? propertyName = null)");
        sb.AppendLine("        {");
        sb.AppendLine("            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));");
        sb.AppendLine("        }");

        // Properties
        foreach (var field in info.Fields)
        {
            sb.AppendLine();
            sb.AppendLine($"        public {field.Type} {field.PropertyName}");
            sb.AppendLine("        {");
            sb.AppendLine($"            get => {field.FieldName};");
            sb.AppendLine("            set");
            sb.AppendLine("            {");
            sb.AppendLine($"                if (!Equals({field.FieldName}, value))");
            sb.AppendLine("                {");
            sb.AppendLine($"                    {field.FieldName} = value;");
            sb.AppendLine("                    OnPropertyChanged();");
            sb.AppendLine("                }");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
        }

        sb.AppendLine("    }");

        if (info.Namespace is not null)
            sb.AppendLine("}");

        return sb.ToString();
    }

    private const string AttributeSource = @"// <auto-generated />
namespace SourceGeneratorDemo.Generators
{
    [System.AttributeUsage(System.AttributeTargets.Field)]
    internal sealed class AutoNotifyAttribute : System.Attribute { }
}
";

    private readonly record struct FieldCandidate(
        string FieldName,
        string FieldType,
        string PropertyName,
        string TypeName,
        string? Namespace,
        string ContainingTypeFullName);

    private readonly record struct FieldInfo(string FieldName, string Type, string PropertyName);

    private readonly record struct NotifyClassInfo(
        string TypeName,
        string? Namespace,
        string FullyQualifiedName,
        ImmutableArray<FieldInfo> Fields);
}
