using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

namespace SourceGeneratorDemo.Generators;

/// <summary>
/// Incremental source generator that produces a ToString() override
/// for any class or struct decorated with [AutoToString].
/// </summary>
[Generator]
public class AutoToStringGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // 1) Inject the marker attribute into the compilation so users
        //    don't need a separate "attributes" package.
        context.RegisterPostInitializationOutput(static ctx =>
        {
            ctx.AddSource("AutoToStringAttribute.g.cs", SourceText.From(AttributeSource, Encoding.UTF8));
        });

        // 2) Build a pipeline that finds every type annotated with [AutoToString].
        IncrementalValuesProvider<TypeToGenerate> pipeline =
            context.SyntaxProvider
                .ForAttributeWithMetadataName(
                    fullyQualifiedMetadataName: "SourceGeneratorDemo.Generators.AutoToStringAttribute",
                    predicate: static (node, _) => node is TypeDeclarationSyntax,
                    transform: static (ctx, _) => GetTypeToGenerate(ctx))
                .Where(static t => t is not null)
                .Select(static (t, _) => t!.Value);

        // 3) Register the output — emit one source file per annotated type.
        context.RegisterSourceOutput(pipeline, static (spc, typeInfo) =>
        {
            var source = GenerateToString(typeInfo);
            spc.AddSource($"{typeInfo.FullyQualifiedName}.AutoToString.g.cs", SourceText.From(source, Encoding.UTF8));
        });
    }

    private static TypeToGenerate? GetTypeToGenerate(GeneratorAttributeSyntaxContext context)
    {
        if (context.TargetSymbol is not INamedTypeSymbol typeSymbol)
            return null;

        var properties = typeSymbol
            .GetMembers()
            .OfType<IPropertySymbol>()
            .Where(p => p.DeclaredAccessibility == Accessibility.Public && !p.IsStatic)
            .Select(p => p.Name)
            .ToImmutableArray();

        var ns = typeSymbol.ContainingNamespace.IsGlobalNamespace
            ? null
            : typeSymbol.ContainingNamespace.ToDisplayString();

        return new TypeToGenerate(
            Name: typeSymbol.Name,
            Namespace: ns,
            FullyQualifiedName: typeSymbol.ToDisplayString().Replace(".", "_"),
            IsRecord: typeSymbol.IsRecord,
            TypeKind: typeSymbol.TypeKind == TypeKind.Struct ? "struct" : "class",
            Properties: properties);
    }

    private static string GenerateToString(TypeToGenerate type)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        if (type.Namespace is not null)
        {
            sb.AppendLine($"namespace {type.Namespace}");
            sb.AppendLine("{");
        }

        sb.AppendLine($"    partial {type.TypeKind} {type.Name}");
        sb.AppendLine("    {");
        sb.AppendLine("        public override string ToString()");
        sb.AppendLine("        {");

        if (type.Properties.Length == 0)
        {
            sb.AppendLine($"            return \"{type.Name} {{}}\";");
        }
        else
        {
            sb.Append($"            return $\"{type.Name} {{{{ ");

            for (int i = 0; i < type.Properties.Length; i++)
            {
                var prop = type.Properties[i];
                if (i > 0) sb.Append(", ");
                sb.Append($"{prop} = {{{prop}}}");
            }

            sb.AppendLine(" }}\";");
        }

        sb.AppendLine("        }");
        sb.AppendLine("    }");

        if (type.Namespace is not null)
        {
            sb.AppendLine("}");
        }

        return sb.ToString();
    }

    private const string AttributeSource = @"// <auto-generated />
namespace SourceGeneratorDemo.Generators
{
    [System.AttributeUsage(System.AttributeTargets.Class | System.AttributeTargets.Struct)]
    internal sealed class AutoToStringAttribute : System.Attribute { }
}
";

    private readonly record struct TypeToGenerate(
        string Name,
        string? Namespace,
        string FullyQualifiedName,
        bool IsRecord,
        string TypeKind,
        ImmutableArray<string> Properties);
}
